// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;

namespace Agencia2.BO
{
	public class SUCURSALES : _SUCURSALES
	{
		public SUCURSALES()
		{
		
		}
	}


    public class SucursalesRecord
    {
        public int SUC_ID { set; get; }

        public string SUC_CODIGO { set; get; }
        public string SUC_DESCRIPCION { set; get; }

        public string SUC_ESTADO { set; get; }
        public int COM_CODIGO { set; get; }
        public int ALM_CODIGO { set; get; }
        public string BLT_UBICACION { set; get; }

    }


    public static class sSucursales
    {

        public static DataView returnView(ref string sMensaje)
        {
            sMensaje = "";
            SUCURSALES oCom = new SUCURSALES();
            try
            {

                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.Query.AddResultColumn("SUC_ID");
                oCom.Query.AddResultColumn("SUC_CODIGO");
                oCom.Query.AddResultColumn("SUC_DESCRIPCION");

                oCom.Query.Load();


            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();


            }

            return oCom.DefaultView;

        }

        public static DataView returnView(int piGrupoId, ref string sMensaje)
        {
            sMensaje = "";
            SUCURSALES oCom = new SUCURSALES();
            try
            {

                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.Query.AddResultColumn("SUC_ID");
                oCom.Query.AddResultColumn("SUC_CODIGO");
                oCom.Query.AddResultColumn("SUC_DESCRIPCION");

                oCom.Where.COM_CODIGO.Value = piGrupoId;
                oCom.Where.COM_CODIGO.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;

                oCom.Query.Load();


            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();


            }

            return oCom.DefaultView;

        }



        public static DataView returnCombo(ref string sMensaje)
        {
            sMensaje = "";
            SUCURSALES oCom = new SUCURSALES();
            try
            {

                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.Query.AddResultColumn("SUC_ID");
                oCom.Query.AddResultColumn("SUC_DESCRIPCION");

                oCom.Query.Load();


            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();


            }
            return oCom.DefaultView;
        }

        public static bool DeleteData(SucursalesRecord pComp, ref string sMensaje)
        {
            bool bRetorno = true;

            try
            {
                SUCURSALES oCom = new SUCURSALES();
                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.LoadByPrimaryKey(pComp.SUC_ID);


                oCom.MarkAsDeleted();

                oCom.Save();

            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();
                bRetorno = false;

            }


            return bRetorno;
        }


        public static bool SaveData(SucursalesRecord pComp, ref string sMensaje, bool bAdiciona)
        {
            bool bRetorno = true;

            try
            {
                SUCURSALES oCom = new SUCURSALES();
                oCom.ConnectionString = Parametros.CadenaConexion;

                if (!bAdiciona)
                    oCom.LoadByPrimaryKey(pComp.SUC_ID);
                else
                {       
                   oCom.AddNew();
                   oCom.COM_CODIGO = pComp.COM_CODIGO;
                  }

                oCom.SUC_CODIGO = pComp.SUC_CODIGO;
                oCom.SUC_DESCRIPCION = pComp.SUC_DESCRIPCION;
                oCom.SUC_ESTADO = pComp.SUC_ESTADO;
                oCom.ALM_CODIGO = pComp.ALM_CODIGO;
                oCom.BLT_UBICACION = pComp.BLT_UBICACION;
             

                oCom.Save();

            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();
                bRetorno = false;

            }


            return bRetorno;
        }

        public static bool ReturnById(int Id, ref SUCURSALES pComp, ref string sMensaje)
        {
            bool bRetorno = true;

            try
            {
                SUCURSALES oCom = new SUCURSALES();
                oCom.ConnectionString = Parametros.CadenaConexion;
                oCom.LoadByPrimaryKey(Id);

                pComp = oCom;


            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();
                bRetorno = false;
            }

            return bRetorno;


        }
    }






}
