// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;


namespace Agencia2.BO
{
	public class COMPANIAS : _COMPANIAS
	{
		public COMPANIAS()
		{
		
		}


	}

    public class CompaniasRecord
    {
        public int COM_CODIGO { set; get; }
        public  string COM_RNC { set; get; }
        public string COM_DESCRIPCION { set; get; }
        public  decimal COM_ANO_PROC { set; get; }
        public decimal COM_MES_PROC { set; get; }
        public  string COM_RESPONSABLE  { set; get; }
        public  string COM_DIRECCION  { set; get; }
        public  string COM_TELEFONO  { set; get; }
        public  string COM_FAX  { set; get; }
        public  string COM_EMAIL  { set; get; }
        public  string COM_ESTADO  { set; get; }
        public  DateTime  COM_FEC_CREA  { set; get; }
        public  string COMA_USR_CREA  { set; get; }
        public  string COM_DIREC_INTERNET  { set; get; }
        public  string COM_RESP_TELEFONO { set; get; }
        public  string COM_RESP_TEL_EXT { set; get; }
        public  string COM_RESP_CARGO { set; get; }
        public  string COM_RESP_EMAIL { set; get; }
        public  string COM_DESCORTA { set; get; }
    }

    public static class sCompania
    {

        public static DataView returnView(ref string sMensaje)
        {
            sMensaje = "";
            COMPANIAS oCom = new COMPANIAS();
            try
            {
               
                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.Query.AddResultColumn("COM_CODIGO");
                oCom.Query.AddResultColumn("COM_DESCORTA");
                oCom.Query.AddResultColumn("COM_DESCRIPCION");

                oCom.Query.Load();
            
                
            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();
              

            }

            return oCom.DefaultView ;

        }

        public static DataView returnCombo(ref string sMensaje)
        {
            sMensaje = "";
            COMPANIAS oCom = new COMPANIAS();
            try
            {

                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.Query.AddResultColumn("COM_CODIGO");
                oCom.Query.AddResultColumn("COM_DESCRIPCION");

                oCom.Query.Load();


            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();


            }
            return oCom.DefaultView;
        }


        public static bool DeleteData(CompaniasRecord pComp, ref string sMensaje)
        {
             bool bRetorno = true;

            try
            {             
                COMPANIAS oCom = new COMPANIAS();
                oCom.ConnectionString = Parametros.CadenaConexion;

               oCom.LoadByPrimaryKey(pComp.COM_CODIGO);


               oCom.MarkAsDeleted();

            oCom.Save();

            }
            catch(Exception ex)
            {
                sMensaje = ex.Message.ToString();
                bRetorno = false;

            }


            return bRetorno;
        }


        public static bool SaveData(CompaniasRecord pComp, ref string sMensaje, bool bAdiciona)
        {
            bool bRetorno = true;

            try
            {             
                COMPANIAS oCom = new COMPANIAS();
                oCom.ConnectionString = Parametros.CadenaConexion;

            if (!bAdiciona)
                oCom.LoadByPrimaryKey(pComp.COM_CODIGO);
            else
                oCom.AddNew();


            oCom.COM_DESCRIPCION = pComp.COM_DESCRIPCION;
            oCom.COM_DESCORTA = pComp.COM_DESCORTA;
            oCom.COM_DESCRIPCION = pComp.COM_DESCRIPCION;
            oCom.COM_RESPONSABLE = pComp.COM_RESPONSABLE;
            oCom.COM_DIRECCION = pComp.COM_DIRECCION;
            oCom.COM_EMAIL = pComp.COM_EMAIL;
            oCom.COM_TELEFONO = pComp.COM_TELEFONO;
            oCom.COM_FAX = pComp.COM_FAX;
            oCom.COM_RNC = pComp.COM_RNC;

            oCom.Save();

            }
            catch(Exception ex)
            {
                sMensaje = ex.Message.ToString();
                bRetorno = false;

            }


            return bRetorno;
        }

        public static bool  ReturnById(int Id,ref COMPANIAS pComp, ref string sMensaje)
        {
            bool bRetorno = true;

            try
            {
                COMPANIAS oCom = new COMPANIAS();
                oCom.ConnectionString = Parametros.CadenaConexion;
                oCom.LoadByPrimaryKey(Id);

                pComp = oCom;


            }
            catch(Exception ex)
            {
               sMensaje = ex.Message.ToString();
               bRetorno=false;
            }

            return bRetorno;


        }
    }


}
