// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;

namespace Agencia2.BO
{
	public class ESTADOS : _ESTADOS
	{
		public ESTADOS()
		{
            //this.GRUPO_EST_ID
            //this.ESTADO_NOMBRE
            //this.ESTADO_ID
            //this.ESTADO_DESCRs
         //_ESTADO_CODIGO
		
		}
	}

    public class EstadosRecord
    {
        public int ESTADO_ID { set; get; }

        public string ESTADO_NOMBRE { set; get; }
        public string ESTADO_DESCR { set; get; }

        public string ESTADO_CODIGO { set; get; }
        public int GRUPO_EST_ID { set; get; }
    }


    public static class sEstados
    {

        public static DataView returnView(ref string sMensaje)
        {
            sMensaje = "";
            ESTADOS oCom = new ESTADOS();
            try
            {

                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.Query.AddResultColumn("ESTADO_ID");
                oCom.Query.AddResultColumn("ESTADO_CODIGO");
                oCom.Query.AddResultColumn("ESTADO_NOMBRE");

                oCom.Query.Load();


            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();


            }

            return oCom.DefaultView;

        }

        public static DataView returnView(int piGrupoId, ref string sMensaje)
        {
            sMensaje = "";
            ESTADOS  oCom = new ESTADOS();
            try
            {

                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.Query.AddResultColumn("ESTADO_ID");
                oCom.Query.AddResultColumn("ESTADO_CODIGO");
                oCom.Query.AddResultColumn("ESTADO_NOMBRE");

                oCom.Where.GRUPO_EST_ID.Value = piGrupoId;
                oCom.Where.GRUPO_EST_ID.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;

                oCom.Query.Load();


            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();


            }

            return oCom.DefaultView;

        }

        public static bool DeleteData(EstadosRecord pComp, ref string sMensaje)
        {
            bool bRetorno = true;

            try
            {
                ESTADOS oCom = new ESTADOS();
                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.LoadByPrimaryKey(pComp.ESTADO_ID);


                oCom.MarkAsDeleted();

                oCom.Save();

            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();
                bRetorno = false;

            }


            return bRetorno;
        }


        public static bool SaveData(EstadosRecord pComp, ref string sMensaje, bool bAdiciona)
        {
            bool bRetorno = true;

            try
            {
                ESTADOS oCom = new ESTADOS();
                oCom.ConnectionString = Parametros.CadenaConexion;

                if (!bAdiciona)
                    oCom.LoadByPrimaryKey(pComp.ESTADO_ID);
                else
                {
                    oCom.AddNew();
                    oCom.GRUPO_EST_ID = pComp.GRUPO_EST_ID;
                }

                oCom.ESTADO_CODIGO = pComp.ESTADO_CODIGO;
                oCom.ESTADO_DESCR = pComp.ESTADO_DESCR;
                oCom.ESTADO_NOMBRE = pComp.ESTADO_NOMBRE;


                oCom.Save();

            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();
                bRetorno = false;

            }


            return bRetorno;
        }

        public static bool ReturnById(int Id, ref ESTADOS pComp, ref string sMensaje)
        {
            bool bRetorno = true;

            try
            {
                ESTADOS oCom = new ESTADOS();
                oCom.ConnectionString = Parametros.CadenaConexion;
                oCom.LoadByPrimaryKey(Id);

                pComp = oCom;


            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();
                bRetorno = false;
            }

            return bRetorno;


        }
    }








}
