// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;

namespace Agencia2.BO
{
	public class SUPLIDORES : _SUPLIDORES
	{
		public SUPLIDORES()
		{
            
		
		}
	}

    public class SuplidoresRecord
    {
        public int SUP_ID { set; get; }

        public string SUP_CODIGO { set; get; }
       
        public string SUP_NOMBRE { set; get; }
        public int ORI_ID { set; get; }
        public string SUP_ESTADO { set; get; }
    }



    public static class sSuplidores
    {

        public static DataView returnView(ref string sMensaje)
        {
            sMensaje = "";
            SUPLIDORES oCom = new SUPLIDORES();
            try
            {

                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.Query.AddResultColumn("SUP_ID");
                oCom.Query.AddResultColumn("SUP_CODIGO");
                oCom.Query.AddResultColumn("SUP_NOMBRE");

                oCom.Query.Load();


            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();


            }

            return oCom.DefaultView;

        }

        public static DataView returnView(int piGrupoId, ref string sMensaje)
        {
            sMensaje = "";
            SUPLIDORES oCom = new SUPLIDORES();
            try
            {

                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.Query.AddResultColumn("SUP_ID");
                oCom.Query.AddResultColumn("SUP_CODIGO");
                oCom.Query.AddResultColumn("SUP_NOMBRE");

                oCom.Where.SUP_ID.Value = piGrupoId;
                oCom.Where.SUP_ID.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;

                oCom.Query.Load();


            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();


            }

            return oCom.DefaultView;

        }

        public static bool DeleteData(SuplidoresRecord pComp, ref string sMensaje)
        {
            bool bRetorno = true;

            try
            {
                SUPLIDORES oCom = new SUPLIDORES();
                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.LoadByPrimaryKey(pComp.SUP_ID);


                oCom.MarkAsDeleted();

                oCom.Save();

            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();
                bRetorno = false;

            }


            return bRetorno;
        }


        public static bool SaveData(SuplidoresRecord pComp, ref string sMensaje, bool bAdiciona)
        {
            bool bRetorno = true;

            try
            {
                SUPLIDORES oCom = new SUPLIDORES();
                oCom.ConnectionString = Parametros.CadenaConexion;

                if (!bAdiciona)
                    oCom.LoadByPrimaryKey(pComp.SUP_ID);
                else
                {
                    oCom.AddNew();
                }

                oCom.SUP_CODIGO = pComp.SUP_CODIGO;
           
                oCom.SUP_NOMBRE = pComp.SUP_NOMBRE;
                oCom.SUP_ESTADO = pComp.SUP_ESTADO;
                oCom.ORI_ID = pComp.ORI_ID ;


                oCom.Save();

            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();
                bRetorno = false;

            }


            return bRetorno;
        }

        public static bool ReturnById(int Id, ref SUPLIDORES pComp, ref string sMensaje)
        {
            bool bRetorno = true;

            try
            {
                SUPLIDORES oCom = new SUPLIDORES();
                oCom.ConnectionString = Parametros.CadenaConexion;
                oCom.LoadByPrimaryKey(Id);

                pComp = oCom;


            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();
                bRetorno = false;
            }

            return bRetorno;


        }
    }


}
