// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;

namespace Agencia2.BO
{
	public class TIPOS : _TIPOS
	{
		public TIPOS()
		{
            //this.s_GRUPO_TIPO_ID
            //this.s_TIPO_CODIGO
            //this.s_TIPO_DESCR
            //this.s_TIPO_ID
            //this.s_TIPO_NOMBRE
          
		
		}
	}

    public class TiposRecord
    {
        public int TIPO_ID { set; get; }

        public string TIPO_CODIGO { set; get; }
        public string TIPO_DESCR { set; get; }

        public string TIPO_NOMBRE { set; get; }
        public int GRUPO_TIPO_ID { set; get; }
    }

    public static class sTipos
    {
        public static DataView returnView(ref string sMensaje)
        {
            sMensaje = "";
            TIPOS oCom = new TIPOS();
            try
            {

                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.Query.AddResultColumn("TIPO_ID");
                oCom.Query.AddResultColumn("TIPO_CODIGO");
                oCom.Query.AddResultColumn("TIPO_NOMBRE");

                oCom.Query.Load();


            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();


            }

            return oCom.DefaultView;

        }

        public static DataView returnView(int piGrupoId, ref string sMensaje)
        {
            sMensaje = "";
            TIPOS oCom = new TIPOS();
            try
            {

                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.Query.AddResultColumn("TIPO_ID");
                oCom.Query.AddResultColumn("TIPO_CODIGO");
                oCom.Query.AddResultColumn("TIPO_NOMBRE");

                oCom.Where.GRUPO_TIPO_ID.Value = piGrupoId;
                oCom.Where.GRUPO_TIPO_ID.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;

                oCom.Query.Load();


            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();


            }

            return oCom.DefaultView;

        }

        public static bool DeleteData(TiposRecord pComp, ref string sMensaje)
        {
            bool bRetorno = true;

            try
            {
                TIPOS oCom = new TIPOS();
                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.LoadByPrimaryKey(pComp.TIPO_ID);


                oCom.MarkAsDeleted();

                oCom.Save();

            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();
                bRetorno = false;

            }


            return bRetorno;
        }


        public static bool SaveData(TiposRecord pComp, ref string sMensaje, bool bAdiciona)
        {
            bool bRetorno = true;

            try
            {
                TIPOS oCom = new TIPOS();
                oCom.ConnectionString = Parametros.CadenaConexion;

                if (!bAdiciona)
                    oCom.LoadByPrimaryKey(pComp.TIPO_ID);
                else
                {
                    oCom.AddNew();
                    oCom.GRUPO_TIPO_ID = pComp.GRUPO_TIPO_ID;
                }

                oCom.TIPO_CODIGO = pComp.TIPO_CODIGO;
                oCom.TIPO_DESCR = pComp.TIPO_DESCR;
                oCom.TIPO_NOMBRE = pComp.TIPO_NOMBRE;


                oCom.Save();

            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();
                bRetorno = false;

            }


            return bRetorno;
        }

        public static bool ReturnById(int Id, ref TIPOS pComp, ref string sMensaje)
        {
            bool bRetorno = true;

            try
            {
                TIPOS oCom = new TIPOS();
                oCom.ConnectionString = Parametros.CadenaConexion;
                oCom.LoadByPrimaryKey(Id);

                pComp = oCom;


            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();
                bRetorno = false;
            }

            return bRetorno;


        }

    }

}
