// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;


namespace Agencia2.BO
{
	public class V2_OPCIONES : _V2_OPCIONES
	{
		public V2_OPCIONES()
		{
		
		}
	}

    public class OpcionesRecord
    {
        public int  OPC_ID  { set; get; }
        public string OPC_NAME { set; get; }
        public string OPC_FORM { set; get; }
        public bool OPC_STATE { set; get; }
        public int OPC_PARENT_ID { set; get; }
    }

    public static class sOpciones
    {


        #region "CRUD"
        

        public static DataView returnCombo()
        {

            DataTable dt = new DataTable();

            V2_OPCIONES oCom = new V2_OPCIONES();
            try
            {

                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.Query.AddResultColumn("OPC_ID");
                oCom.Query.AddResultColumn("OPC_NAME");

            

                oCom.Query.Load();

                dt = oCom.DefaultView.Table.Copy();

                DataRow dr = dt.NewRow();
                dr[0] = 0;
                dr[1] = "[SIN PADRE]";

                dt.Rows.Add(dr);




            }
            catch (Exception ex)
            {
             


            }

            return dt.DefaultView;

        }


        public static DataView returnView(ref string sMensaje)
        {
            sMensaje = "";
            V2_OPCIONES oCom = new V2_OPCIONES();
            try
            {

                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.Query.AddResultColumn("OPC_ID");
                oCom.Query.AddResultColumn("OPC_NAME");
                oCom.Query.AddResultColumn("OPC_STATE");
                oCom.Query.AddResultColumn("OPC_PARENT_ID");
           

                oCom.Query.Load();


            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();


            }

            return oCom.DefaultView;

        }

        public static bool DeleteData(OpcionesRecord pComp, ref string sMensaje)
        {
            bool bRetorno = true;

            try
            {
                V2_OPCIONES oCom = new V2_OPCIONES();
                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.LoadByPrimaryKey(pComp.OPC_ID);


                oCom.MarkAsDeleted();

                oCom.Save();

            }
            catch (Exception ex)
            {
                sMensaje = ex.Message.ToString();
                bRetorno = false;

            }

            return bRetorno;
        }

        public static bool SaveData(OpcionesRecord pComp, ref string sMensaje, bool bAdiciona)
        {
            bool bRetorno = true;

            try
            {             
                V2_OPCIONES oCom = new V2_OPCIONES();
                oCom.ConnectionString = Parametros.CadenaConexion;

            if (!bAdiciona)
                oCom.LoadByPrimaryKey(pComp.OPC_ID);
            else
                oCom.AddNew();


            oCom.OPC_NAME = pComp.OPC_NAME;
            oCom.OPC_STATE = pComp.OPC_STATE;
            oCom.OPC_PARENT_ID = pComp.OPC_PARENT_ID;
            oCom.OPC_FORM = pComp.OPC_FORM;
         

            oCom.Save();

            }
            catch(Exception ex)
            {
                sMensaje = ex.Message.ToString();
                bRetorno = false;

            }


            return bRetorno;
        }

        public static bool ReturnById(int Id, ref V2_OPCIONES pComp, ref string sMensaje)
            {
                bool bRetorno = true;

                try
                {
                    V2_OPCIONES oCom = new V2_OPCIONES();
                    oCom.ConnectionString = Parametros.CadenaConexion;
                    oCom.LoadByPrimaryKey(Id);

                    pComp = oCom;


                }
                catch (Exception ex)
                {
                    sMensaje = ex.Message.ToString();
                    bRetorno = false;
                }

                return bRetorno;


            }
        
        #endregion

        #region "Manejo"

        public static DataView RetornaOpcMenu()
        {

            V2_OPCIONES oCom = new V2_OPCIONES();
            try
            {

                oCom.ConnectionString = Parametros.CadenaConexion;

                oCom.Query.AddResultColumn("OPC_ID");
                oCom.Query.AddResultColumn("OPC_NAME");
                oCom.Query.AddResultColumn("OPC_FORM");
                oCom.Query.AddResultColumn("OPC_PARENT_ID");

                oCom.Where.OPC_STATE.Value = 1;
                oCom.Where.OPC_STATE.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;

                oCom.Query.AddOrderBy("OPC_ID", MyGeneration.dOOdads.WhereParameter.Dir.ASC);


                oCom.Query.Load();


            }
            catch (Exception ex)
            {
               


            }

            return oCom.DefaultView;

        }
        

        #endregion

    }

}
